### ISSUE TITLE
process-new-granules fails with `ASFWKTError`

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3#1141]
The `process-new-granules` lambda evaluates subscriptions and submits jobs for them. A user can create a subscription with an invalid `subscription.search_parameters.intersectsWith` value that causes the lambda to throw an `asf_search.ASFWKTError` exception, halting evaluation of subscription and preventing jobs from being submitted for other subscriptions.

```
[ERROR] ASFWKTError: WKT string: "POLYGON ((41.766 8.9121, 41.766 8.9121, 41.766 8.9121, 41.766 8.9121))" is not a valid WKT string
Traceback (most recent call last):
  File "/var/task/process_new_granules.py", line 79, in lambda_handler
    handle_subscription(subscription)
  File "/var/task/process_new_granules.py", line 68, in handle_subscription
    jobs = get_jobs_for_subscription(subscription, limit=20)
  File "/var/task/process_new_granules.py", line 54, in get_jobs_for_subscription
    granules = get_unprocessed_granules(subscription)
  File "/var/task/process_new_granules.py", line 18, in get_unprocessed_granules
    search_results = asf_search.search(**dynamo.util.convert_decimals_to_numbers(subscription['search_parameters']))
  File "/var/task/asf_search/search/search.py", line 131, in search
    opts.intersectsWith = validate_wkt(data['intersectsWith']).wkt
  File "/var/task/asf_search/WKT/validate_wkt.py", line 33, in validate_wkt
    raise ASFWKTError(f'WKT string: \"{aoi_shape.wkt}\" is not a valid WKT string')
```
    
We verify that `intersectsWith` is valid WKT in our API specification using the `wkt` format at https://github.com/ASFHyP3/hyp3/blob/develop/apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2#L467 , but `asf_search.search` throws an exception for some syntactically-valid WKT strings, such as a Polygon with repeated points, e.g. `POLYGON ((41.766 8.9121, 41.766 8.9121, 41.766 8.9121, 41.766 8.9121))`

**Comment by asjohnston-asf** [comment]
With the release of HyP3 v2.21.2, subscriptions are now evaluated using a manager/worker workflow. This issue will no longer cause the manager to fail, so it will attempt to evaluate all subscriptions even if one or more subscriptions have bad WKT values. I expect the worker run for that particular subscription to still fail, though, so no jobs would be submitted for that subscription.
