### ISSUE TITLE
Include AWS request ID in subscription manager/worker log records for unhandled exceptions

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3#1286]
When the subscription manager or worker lambda crashes due to an unhandled exception, the AWS request ID is not included in the corresponding log record. Run the following query in CloudWatch Logs Insights for the subscription worker log group in the `edc-prod` account (setting start date to `2022/10/01` currently yields 16 matching records) to observe the missing `@requestId` field:

```
fields @timestamp, @requestId, @message, @logStream
| filter @message like /ERROR/
```

This breaks the subscription worker error summary script in https://github.com/ASFHyP3/hyp3-operations. Perhaps there's a special AWS-provided fix for this problem (similar to how they provide built-in logging configuration for Lambda), or it should be easily resolved by just logging all unhandled exceptions (with traceback) in the lambda handlers.

Validate in test:
- [x] Unhandled exceptions are now being logged with all the usual fields, including request ID. The easiest way to validate this would be to invoke the Subscription Worker with a disabled subscription and confirm that the logs show an unhandled `ValueError`.

Validate in prod:
- [x] Same as for test.

**Comment by jtherrmann** [comment]
I think I actually prefer manually closing issues following successful validation.

**Comment by jtherrmann** [comment]
Unfortunately overriding `sys.excepthook` does not seem to work, see https://github.com/gkrizek/leh

**Comment by jtherrmann** [comment]
After confirming this problem, if there are no better solutions for logging unhandled exceptions in AWS Lambda, one possibility is to use a decorator to wrap the lambda handler in a try/except to log unhandled exceptions.

**Comment by jtherrmann** [comment]
I invoked the Subscription Worker in `hyp3-edc-uat` with:

```
aws lambda invoke --profile edc-uat --function-name hyp3-edc-uat-SubscriptionWorker-SXLTCW5M16V-Lambda-E45yTNfsjejo --payload '{"subscription": {"subscription_id": "foo", "user_id": "jth", "enabled": false}}' --cli-binary-format raw-in-base64-out /dev/stdout
```

And confirmed that the log stream looks as expected:

```
START RequestId: 80a4bc7b-a49b-418d-9d06-3ef821ee09f4 Version: $LATEST
[INFO]	2022-12-14T01:36:13.023Z	80a4bc7b-a49b-418d-9d06-3ef821ee09f4	Handling subscription foo for user jth
[ERROR]	2022-12-14T01:36:13.023Z	80a4bc7b-a49b-418d-9d06-3ef821ee09f4	Unhandled exceptionTraceback (most recent call last):  File "/var/task/lambda_logging/__init__.py", line 15, in wrapper    lambda_handler(event, context)  File "/var/task/subscription_worker.py", line 80, in lambda_handler    raise ValueError(f'subscription {subscription["subscription_id"]} is disabled')ValueError: subscription foo is disabled
RequestId: 80a4bc7b-a49b-418d-9d06-3ef821ee09f4 Error: Runtime exited with error: exit status 1Runtime.ExitError
END RequestId: 80a4bc7b-a49b-418d-9d06-3ef821ee09f4
```
